=== MattWongCode4U/COMP4711-Lab07/data/timetable.dtd
<!--Noted as being timetable as main, day inner, time, inner of day, course inner of day/time-->
<!ELEMENT timetable (days, periods, course)>
<!ATTLIST timetable year (2014|2015|2016|2017) #REQUIRED
	  term (1|2|3|4) #REQUIRED>

<!ELEMENT days (dayoftheweek*)>
<!ATTLIST dayoftheweek day (mon|tue|wed|thu|fri) #REQUIRED>

<!ELEMENT period (timeblock*)>
<!ELEMENT timeblock (booking)>
<!ATTLIST timeblock time (8:30|9:30|11:30|12:30|13:30|14:30|15:30|16:30) #REQUIRED>

<!ELEMENT courses (course)>
<!ELEMENT course (info*)>
<!ATTLIST course course (BLAW3600|COMP4560|COMP4711|COMP4735|COMP4932|COMP4932) #REQUIRED>

<!ELEMENT info (building,room,instructor,time?,day?,class?)>
<!ATTLIST info type (lecture|lab) #REQUIRED>
	<!ELEMENT building (#PCDATA)>
	<!ELEMENT room (#PCDATA)>
	<!ELEMENT instructor (#PCDATA)>
	<!ELEMENT time (#PCDATA)>
	<!ELEMENT day (#PCDATA)>
	<!ELEMENT class (#PCDATA)>

=== MattWongCode4U/COMP4711-Lab07/data/day.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "timetable.dtd">

<timetable year="2016" term="4">
	<days>
		<dayoftheweek day="mon">
			<info type="lab">
				<building>SE-12</building>
				<room>308</room>
				<instructor>Dennis Richards</instructor>
				<time>8:30</time>
				<class>COMP4932</class>
			</info>
			<info type="lecture">
				<building>SW-1</building>
				<room>1205</room>
				<instructor>Mirela Gutica</instructor>
				<time>11:30</time>
				<class>COMP4735</class>
			</info>
			<info type="lab">
				<building>SE-12</building>
				<room>308</room>
				<instructor>Dennis Richards</instructor>
				<time>14:30</time>
				<class>COMP4995</class>
			</info>
		</dayoftheweek>
	    <dayoftheweek day="tue">
	        <info type="lab">
	            <building>SE-12</building>
	            <room>320</room>
	            <instructor>Brenda Fine</instructor>
	            <time>9:30</time>
	            <class>COMP4560</class>
	        </info>
	        <info type="lecture">
	            <building>SW-5</building>
	            <room>1850</room>
	            <instructor>Brenda Fine</instructor>
	            <time>11:30</time>
	            <class>COMP4560</class>
	        </info>
	        <info type="lecture">
	            <building>SW-5</building>
	            <room>1840</room>
	            <instructor>James Parry</instructor>
	            <time>14:30</time>
	            <class>COMP4711</class>
	        </info>
	        <info type="lecture">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <time>15:30</time>
	            <class>COMP4932</class>
	        </info>
	    </dayoftheweek>
	    <dayoftheweek day="wed">
	        <info type="lab">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Matthew Linder</instructor>
	            <time>8:30</time>
	            <class>COMP4735</class>
	        </info>
	        <info type="lecture">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <time>10:30</time>
	            <class>COMP4995</class>
	        </info>
	        <info type="lecture">
	            <building>SE-1</building>
	            <room>1205</room>
	            <instructor>Mirela Gutica</instructor>
	            <time>13:30</time>
	            <class>COMP4735</class>
	        </info>
	    </dayoftheweek>
	    <dayoftheweek day="thu">
	        <info type="lecture">
	            <building>SW-3</building>
	            <room>1710</room>
	            <instructor>Mirela Gutica</instructor>
	            <time>11:30</time>
	            <class>COMP4735</class>
	        </info>
	        <info type="lab">
	            <building>Sw-3</building>
	            <room>4725</room>
	            <instructor>Catherine Ryan</instructor>
	            <time>13:30</time>
	            <class>BLAW3600</class>
	        </info>
	        <info type="lab">
	            <building>SE-12</building>
	            <room>310</room>
	            <instructor>James Parry</instructor>
	            <time>15:30</time>
	            <class>COMP4711</class>
	        </info>
	    </dayoftheweek>
	    <dayoftheweek day="fri">
	        <info type="lecture">
	            <building>SW-5</building>
	            <room>1840</room>
	            <instructor>Catherine Ryan</instructor>
	            <time>8:30</time>
	            <class>BLAW3600</class>
	        </info>
	        <info type="lecture">
	            <building>SW-3</building>
	            <room>1750</room>
	            <instructor>Brenda Fine</instructor>
	            <time>12:30</time>
	            <class>COMP4560</class>
	        </info>
	    </dayoftheweek>
	</days>
</timetable>

=== MattWongCode4U/COMP4711-Lab07/data/period.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "timetable.dtd">

<timetable year="2016" term="4">
	<periods>
		<timeblock time="8:30">
			<info type="lab">
				<building>SE-12</building>
				<room>308</room>
				<instructor>Dennis Richards</instructor>
				<day>mon</day>
				<class>COMP4932</class>
			</info>
			<info type="lab">
				<building>SE-12</building>
				<room>308</room>
				<instructor>Mathew Linder</instructor>
				<day>wed</day>
				<class>COMP4735</class>
			</info>
			<info type="lecture">
				<building>SW-5</building>
				<room>1840</room>
				<instructor>Catherine Ryan</instructor>
				<day>fri</day>
				<class>BLAW3600</class>
			</info>
		</timeblock>
	    <timeblock time="9:30">
	        <info type="lab">
	            <building>SE-12</building>
	            <room>320</room>
	            <instructor>Brenda Fine</instructor>
	            <day>tue</day>
	            <class>COMP4560</class>
	        </info>	        
	    </timeblock>
	    <timeblock time="10:30">
	        <info type="lecture">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <day>wed</day>
	            <class>COMP4995</class>
	        </info>
	    </timeblock>
	    <timeblock time="11:30">
	        <info type="lecture">
	            <building>SW-1</building>
	            <room>1205</room>
	            <instructor>Mirela Gutica</instructor>
	            <day>mon</day>
	            <class>COMP4735</class>
	        </info>
			<info type="lecture">
	            <building>SW-5</building>
	            <room>1850</room>
	            <instructor>Brenda Fine</instructor>
	            <day>tue</day>
	            <class>COMP4560</class>
	        </info>
	        <info type="lab">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <day>wed</day>
	            <class>COMP4995</class>
	        </info>
			<info type="lecture">	
	            <building>SW-3</building>
	            <room>1710</room>
	            <instructor>Mirela Gutica</instructor>
	            <day>thu</day>
	            <class>COMP4735</class>
	        </info>
	    </timeblock>
	    <timeblock time="12:30">
	        <info type="lecture">
	            <building>SW-3</building>
	            <room>1750</room>
	            <instructor>Brenda Fine</instructor>
	            <day>fri</day>
	            <class>COMP4560</class>
	        </info>
	    </timeblock>
		<timeblock time="13:30">
	        <info type="lecture">
	            <building>SW-1</building>
	            <room>1205</room>
	            <instructor>Mirela Gutica</instructor>
	            <day>wed</day>
	            <class>COMP4735</class>
	        </info>
			<info type="lab">
	            <building>SW-3</building>
	            <room>4725</room>
	            <instructor>Catherine Ryan</instructor>
	            <day>thu</day>
	            <class>BLAW3600</class>
	        </info>
	    </timeblock>
		<timeblock time="14:30">
	        <info type="lab">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <day>mon</day>
	            <class>COMP4995</class>
	        </info>
	        <info type="lecture">
	            <building>SW-5</building>
	            <room>1840</room>
	            <instructor>James Parry</instructor>
	            <day>tue</day>
	            <class>COMP4711</class>
	        </info>
	    </timeblock>
		<timeblock time="15:30">
	        <info type="lecture">
	            <building>SE-12</building>
	            <room>308</room>
	            <instructor>Dennis Richards</instructor>
	            <day>tue</day>
	            <class>COMP4932</class>
	        </info>
	        <info type="lab">
	            <building>SE-12</building>
	            <room>310</room>
	            <instructor>James Parry</instructor>
	            <day>thu</day>
	            <class>COMP4711</class>
	        </info>
	    </timeblock>
	</periods>
</timetable>
